### ISSUE TITLE
Rounding / appearance Issues with Item Stock Levels dashboard

### ISSUE THREAD

**Issue by Gwalior-84** [openmsupply/msupply-dashboard#109]
There are a couple of number format issues on [dashboard ](https://png.msupply.org:3000/d/vS1Fd2bZz/item-stock-levels?orgId=1&var-multiFacility=Hagen%20GH%20Main%20Store&var-facilityFilter=&var-codeStart=&var-code=All&var-nameCategory1=All&var-nameCategory1Level2=All&var-nameCategory1Level1=All&var-nameCategory2=Regional%20Hospital&var-nameCategory3=All&var-nameCategory4=All&var-nameCategory5=All&var-nameCategory6=All&var-organisation=All&var-mode=All&var-disabled=All&var-singleFacility=Hagen%20GH%20Main%20Store&var-itemCategory=All&var-itemCategoryLevel2=All&var-itemCategoryLevel1=All&var-itemCategory2=All&var-itemCategory3=All&var-venCategory=V&var-stockType=On%20essential%20drug%20list&var-stockLevel=All&var-itemFilter=&var-multiItem=All&var-singleItem=Adrenaline%20Injection,%201:1000,%201ml&var-nullString=NONE&var-storeTableName=store_categories&var-itemTableName=item_categories&var-facilityCount=1&var-itemCount=74&var-sqlRestriction=).

![image](https://user-images.githubusercontent.com/9062300/84616936-c2289b00-af10-11ea-85fb-897d9dcb5355.png)

Issues:

- Item 103600, MOS:  Visualization rules clearly state 2 decimal places.  What happened here?
- Item 103100, AMC:  As a general principle, we should round to 3, or at max, 4 significant places.  Does Grafana allow that?
- Actual numbers (as distinct from strings that happen to be numbers, e.g. Item Code) should generally be right-justified.  Does Grafana allow that?

**Comment by CarlosNZ** [comment]
> * Item 103600, MOS:  Visualization rules clearly state 2 decimal places.  What happened here?

You want the decimals to show even for whole numbers? Okay, I've changed the unit to `none` which forces the 2dp on all entries.

> * Item 103100, AMC:  As a general principle, we should round to 3, or at max, 4 significant places.  Does Grafana allow that?

Not really, the closest we can do is use the "short" unit, which presents the values with the metric suffixes K=1000, M=1,000,000 etc. I've switched that on for now. Do you think that'll work, or is it confusing?
![Screen Shot 2020-06-15 at 4 33 29 PM](https://user-images.githubusercontent.com/5456533/84618337-f9ee0d80-af25-11ea-9dd8-78d7692f6238.png)

> * Actual numbers (as distinct from strings that happen to be numbers, e.g. Item Code) should generally be right-justified.  Does Grafana allow that?

Not currently, but this is possible in Grafana 7.0x :)

**Comment by Gwalior-84** [comment]
> You want the decimals to show even for whole numbers? Okay, I've changed the unit to `none` which forces the 2dp on all entries.

Thank you.  The consistency is beautiful.

> Not really, the closest we can do is use the "short" unit, which presents the values with the metric suffixes K=1000, M=1,000,000 etc. I've switched that on for now. Do you think that'll work, or is it confusing?

I think this will work well.  Thank you!  Indeed, I argue that this would be a better unit for the other two columns (SOH and MOS) as well.  I've updated accordingly.


> Not currently, but this is possible in Grafana 7.0x :)
Oh well, we can live with this 😄
