### ISSUE TITLE
Stock per item for selected stores

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/msupply-dashboard#113]
From Section 3.5.3 of https://drive.google.com/file/d/1lMHoybnZstfrhpPsswvn3O9i-dv8jxMH/view

Partly covered by [Item Stock Levels](https://png.msupply.org:3000/d/vS1Fd2bZz/item-stock-levels?orgId=1)

there are differences in the requested version though.

The stock on hand data will be shown in a table as shown below:

| Item Code | Item Name | Default Pack size | SoH (packs) | SoH (months) |
| -- | -- | -- | -- | -- |
| abc | Item ABC  | 1  | 0 | 0 | 

There will be a row of data for each selected item, across all selected stores. Rows will be colour coded according to months of stock (based on last 12 months’ of usage):

- Less than 6 months of stock = Red
- More than 6 months but less than 12 months of stock = Amber
- More than 12 months of stock= Green

#### Notes:
- **Selected stores**: Need to be able to easily select stores by programme (e.g., all the TB programme
 stores) and this selection will be set as default by the login credentials.
- **Selected items**: Need to be able to easily select items by programme (e.g., all the TB programme
 items) and this selection will be set as default by the login credentials.
- **Selected time periods**: Need to be able to easily select time periods (e.g., today, this week, this
 month, this quarter etc. Should include ‘for all time’) and this selection will be set as default by the
 login credentials.

**Comment by Gwalior-84** [comment]
This is effectively done:  https://png.msupply.org:3000/d/9gnQQXMMk/item-stock-levels-morobe?orgId=1
