### ISSUE TITLE
Item stock levels panel - add Stock on Order (SOO) column

### ISSUE THREAD

**Issue by Gwalior-84** [openmsupply/msupply-dashboard#120]
We have received a request for this panel to be enhanced with the addition of a 'Stock on Order' column at the right.

![image](https://user-images.githubusercontent.com/9062300/87101742-3b5aaa00-c293-11ea-957b-7d56745850a6.png)

This column would include the number of units (not months) of stock on order.  This is a sum of all outstanding lines on:

- Requisitions with status = `cn `_and_ 
- Purchase orders with status = `cn`

A Mobile store can only have requisitions.  A desktop store can have both requisitions and purchase orders.

Should be done in conjunction with #138

**Comment by CarlosNZ** [comment]
@mark-prins Don't suppose you know which of the values in `purchase_order_line` is the number of units we're looking for?
We have:

- `quan_original_order`
- `quan_adjusted_order`
- `quan_rec_to_date`

Or is it something else altogether?

Similarly, for `requisition_line` -- I assume we want `actualquan`?

**Comment by Gwalior-84** [comment]
@CarlosNZ for purchase orders, I know it is `quan_adjusted_order`  For requisitions, it [looks like](https://docs.msupply.org.nz/tables_fields:main_tables:requisition#requisition_line) `actualquan` is it.

**Comment by mark-prins** [comment]
Yep, `quan_adjusted_order` and 🤷‍♂️  but it looks like it's `actualquan`, as Mark says.

**Comment by Gwalior-84** [comment]
Looks fantastic @CarlosNZ !
