### ISSUE TITLE
Item stock levels panel - add ability to filter by Item Master list

### ISSUE THREAD

**Issue by Gwalior-84** [openmsupply/msupply-dashboard#121]
We have received a request for this panel to be enhanced with the ability to filter to include only those items that are on a selected Master list.

![image](https://user-images.githubusercontent.com/9062300/87113595-f8f49580-c2b1-11ea-8ad2-b9763c828629.png)

**Comment by mark-prins** [comment]
Hi @Gwalior-84 - the `Master list` filter has been added in. 

The master list filters the `item` filter which in turn filters the table. See what you think.

**Comment by Gwalior-84** [comment]
This looks great @mark-prins , it seems to be working well.  Thanks!
