### ISSUE TITLE
Sync sites panel not showing version number / release date for Mobile stores

### ISSUE THREAD

**Issue by Gwalior-84** [openmsupply/msupply-dashboard#125]
Dashboard: https://png.msupply.org:3000/d/KK-crfJWk/sync-statistics-2020?orgId=1

![image](https://user-images.githubusercontent.com/9062300/87391653-7f7ce000-c5ee-11ea-8d27-b6610a7161d9.png)

If the sync site is Mobile, the Version and Release Date are not displayed.  Release date is of marginal value.  Version is of much greater value.

I expect mSupply version number to be displayed for all sites, perhaps with indicator of whether it is Mobile or Desktop.

**Comment by mark-prins** [comment]
The version of mobile stores isn't available centrally (yet). I propose this: https://github.com/sussol/msupply/issues/6618 to address the problem.

**Comment by Gwalior-84** [comment]
Thanks @mark-prins .  Looks great!
