### ISSUE TITLE
Sync sites panel to include sync out records waiting

### ISSUE THREAD

**Issue by Gwalior-84** [openmsupply/msupply-dashboard#126]
Dashboard: https://png.msupply.org:3000/d/KK-crfJWk/sync-statistics-2020?orgId=1

It would be useful to see here which sites have a significant number of sync out records waiting:

![image](https://user-images.githubusercontent.com/9062300/87392098-4729d180-c5ef-11ea-8f8d-5227a06a3061.png)

The numbers would be the same as in Desktop Help > About mSupply... > Show sync records:

![image](https://user-images.githubusercontent.com/9062300/87392419-d931da00-c5ef-11ea-93a6-1943d39764ae.png)

**Comment by mark-prins** [comment]
added records waiting column.
Note: when the server is upgraded to v12 we can tidy the query, as the `site` table will contain the version of desktop clients as well as mobile.

**Comment by Gwalior-84** [comment]
> 
> 
> added records waiting column.
> Note: when the server is upgraded to v12 we can tidy the query, as the `site` table will contain the version of desktop clients as well as mobile.

Fantastic!  Version 12 is supposed to be coming out later this week.  We'll upgrade PNG as soon as that happens, as they are waiting for a couple of things there.

**Comment by Gwalior-84** [comment]
This is now done.  Thanks @mark-prins
