### ISSUE TITLE
Add product satisfaction dashboard

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/msupply-dashboard#127]
Nb. This is just copied straight from the Ivory Coast spec I was sent. Gary may have more information. 

Specification no: EXF42b 

Sustainable Solutions will create 2 new dashboard reports, one for the Product satisfaction rate and the other for the Programme satisfaction rate:

Product satisfaction rate will look like this:

![image](https://user-images.githubusercontent.com/29744386/87629534-5479c400-c787-11ea-90b6-44583c1a212a.png)

There will be 1 line for every item in the datafile or which matches the filters chosen.
There will be filters for region, district, facility and programme.
The satisfaction rate figures will be coloured green for 95% and above, yellow between 85 and 95% and red for less than 85%.

The calculation of satisfaction rate will be:

Satisfaction rate = N/D x 100

Where N = Number of product lines delivered with a line satisfaction rate of 85% or more for non-tracer products and 95% or more for tracer products (the line satisfaction rate  = S/R x 100 where S = the quantity delivered (comes from the supplier invoices) and R = the quantity requested for a line (comes from the originating requisitions)).
D = Total number of product lines ordered (comes from the requisitions).

Please note, items will be identified as being a tracer by the setting in the item’s details highlighted in this screenshot (if it is ticked, it is a tracer item):

![image](https://user-images.githubusercontent.com/29744386/87629740-b3d7d400-c787-11ea-925e-fedcd3f6abf0.png)

**Comment by mark-prins** [comment]
@DhanyaHerath this one? https://ci.msupply.org:3000/d/bYIlWbcWz/taux-de-satisfaction?orgId=1

**Comment by DhanyaHerath** [comment]
Ha. that's probably it! But will let @GaryWillets have the final say :)

**Comment by DhanyaHerath** [comment]
It's been a while and I'm fairly sure these are the correct dashboard reports, so closing
