### ISSUE TITLE
Add programme satisfaction rate dashboard 

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/msupply-dashboard#128]
Nb. This is just copied straight from the Ivory Coast spec I was sent. Gary may have more information. 

Specification no: EXF42b 

Programme satisfaction rate will look like this:
![image](https://user-images.githubusercontent.com/29744386/87629680-973b9c00-c787-11ea-8423-cecd96e5e148.png)

There will be 1 line for every programme in the datafile.
There will be filters for region, district and facility.
The satisfaction rate figures will be coloured green for 95% and above, yellow between 85 and 95% and red for less than 85%.

The calculation of satisfaction rate will be:

Satisfaction rate = N/D x 100

Where N = Number of product lines delivered with a line satisfaction rate of 85% or more for non-tracer products and 95% or more for tracer products (the line satisfaction rate  = S/R x 100 where S = the quantity delivered (comes from the supplier invoices) and R = the quantity requested for a line (comes from the originating requisitions)).
D = Total number of product lines ordered (comes from the requisitions).

Please note, items will be identified as being a tracer by the setting in the item’s details highlighted in this screenshot (if it is ticked, it is a tracer item):

![image](https://user-images.githubusercontent.com/29744386/87629740-b3d7d400-c787-11ea-925e-fedcd3f6abf0.png)

**Comment by mark-prins** [comment]
@DhanyaHerath @GaryWilletts - on [this dashboard](https://ci.msupply.org:3000/d/bYIlWbcWz/taux-de-satisfaction?orgId=1)

**Comment by DhanyaHerath** [comment]
It's been a while and I'm fairly sure these are the correct dashboard reports, so closing
