### ISSUE TITLE
Store performance indicators panel filter should be for Category 2 fields

### ISSUE THREAD

**Issue by Gwalior-84** [openmsupply/msupply-dashboard#132]
Current behaviour:

Sync Statistics 2020 dashboard > Store performance indicators panel has a **Filter** that appears to filter by text in the store name.

![image](https://user-images.githubusercontent.com/9062300/88496588-feb3e000-d000-11ea-81f2-51eaf9d340c4.png)

Desired behaviour:  This filter should be replaced with a filter on Category 2 as is used in the Item Stock Levels Morobe dashboard:

![image](https://user-images.githubusercontent.com/9062300/88496654-3ae74080-d001-11ea-88de-26f79dba9bc5.png)

**Comment by CarlosNZ** [comment]
Have updated this now. The Store Type (Category 2) _is_ including the "AMS" stores, unlike on the Stock Levels table. Is this what you want?

**Comment by Gwalior-84** [comment]
Perfect!  Thanks @CarlosNZ !
