### ISSUE TITLE
Make Master List Analysis dashboard pick all valid stores

### ISSUE THREAD

**Issue by Gwalior-84** [openmsupply/msupply-dashboard#133]
Current behaviour:

Master List Analysis dashboard & panel:  https://png.msupply.org:3000/d/vN3z_5qWk/master-list-analysis?orgId=1

![image](https://user-images.githubusercontent.com/9062300/88864493-aec75a00-d248-11ea-86ef-4d0f6316bdd5.png)

Does not include recently (within the last month) added stores.  There are at least two more stores with names starting with `mad`

Desired behaviour:

The dashboard should pick up all stores as they are added to mSupply.

**Comment by CarlosNZ** [comment]
Should be sorted now.
(The variable was set to refresh "Never", rather than "On dashboard load")
Also made the store list Alphabetical ordered.

**Comment by Gwalior-84** [comment]
Thanks @CarlosNZ !  Works brilliantly!

OK, I think I found where the refresh setting is, so I can look for this in future:

![image](https://user-images.githubusercontent.com/9062300/88891760-0c7a9700-d287-11ea-8e8b-6c8c8f8b1d05.png)

Is the alphabetical sorting something that I could fix?

**Comment by CarlosNZ** [comment]
> Is the alphabetical sorting something that I could fix?

It's just a matter of specifying the `order by` in the SQL query. :)

**Comment by mark-prins** [comment]
> Is the alphabetical sorting something that I could fix?

@Gwalior-84 or, if there isn't an `order by` then changing the `Sort` drop down will do it.

**Comment by Gwalior-84** [comment]
> 
> 
> > Is the alphabetical sorting something that I could fix?
> 
> @Gwalior-84 or, if there isn't an `order by` then changing the `Sort` drop down will do it.

Is there a `Sort` drop down on the filter @mark-prins ?

**Comment by mark-prins** [comment]
ah, no sorry. when editing a variable, there's an option to have it sorted.
I was referring to the screenshot above (https://github.com/openmsupply/msupply-dashboard/issues/133#issuecomment-666173558)
