### ISSUE TITLE
Item stock levels panel - add Preferred pack size (Pref. pack) column

### ISSUE THREAD

**Issue by Gwalior-84** [openmsupply/msupply-dashboard#138]
We have received a request (https://support.msupply.org.nz/cerb6/profiles/ticket/DK-7691-SN/conversation) for this panel to be enhanced with the addition of a Preferred pack size (Pref. pack) column to the left of the SOH column.

![image](https://user-images.githubusercontent.com/9062300/89157671-41049080-d5b0-11ea-8bdd-489bf8045ef2.png)

This column would show the Preferred pack size value for the item:

![image](https://user-images.githubusercontent.com/9062300/89157811-71e4c580-d5b0-11ea-9d3f-d3a055b7b011.png)

Should be done in conjunction with #120

**Comment by CarlosNZ** [comment]
Hi @Gwalior-84 ,
just to clarify -- we should do this to the **Morobe** dashboard and you'll take care of copying it to the other PHAs? I see you've already made quite a few others, so are you fine with progressing this way? Is there likely to be more changes to the layout that you'll have to apply to all the others?

Just wondering if there's a more efficient way to proceed. I'll make these adjustments to Morobe for now.

**Comment by Gwalior-84** [comment]
Yes, @CarlosNZ , Morobe is the master.  Once that is functioning well, I will copy it to the other PHAs and programmes folders

**Comment by CarlosNZ** [comment]
Have added this column now.

Working on #120, but need to figure out which database values we're interested in.

**Comment by Gwalior-84** [comment]
Beautiful @CarlosNZ !
