### ISSUE TITLE
Add overall reporting rate dashboard report : D1

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/msupply-dashboard#143]
Original specs: https://docs.google.com/document/d/1TmDxlU48-738xP8PgF6yEb7CbL8TbH77/edit
Excel Mockup: https://docs.google.com/spreadsheets/d/1SJLUUf4u0RCu9toaueW2iSao-ughOaGbbrvjqV4Sq9I/edit#gid=1970684248

Requested: 

> On time reporting rate: 
> - listing of facilities that did not submit their report 
> - List of facilities that that did not submit their report on time

- Query for whether any customer requisitions have been made for each facility over a given period
- Add `Period` filter 
- Report due date = end date of the period
- Colour code by whether the report was on time or not 

![image](https://user-images.githubusercontent.com/29744386/96798170-c9caf400-145c-11eb-9baa-0816b9cf0428.png)

## Due date 

December 20th 

## Job Code 

JSIFIJ01 | JSI-FIJI-UNFPA Work 2nd half 2020

**Comment by Mai21** [comment]
Still need to check the reliability of data but anyway here is draft.
https://demo-board.msupply.org:3000/goto/EFNeKBfGk

**Comment by Mai21** [comment]
<table>
<tr><th>Facility</th><td>[store]name using selected mater list</td></tr>
<tr><th>Report due</th><td>[period]endDate from selected period</td></tr>
<tr><th>Report submitted</th><td>[requisition]entry_date</td></tr>
<tr><th>On time</th><td>Yes : Report submitted <= Report due, Nope : Report submitted > Report due , Not submitted : No requisition</td></tr>
</table>
