### ISSUE TITLE
Add data quality dashboard report : D2

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/msupply-dashboard#144]
Original specs: https://docs.google.com/document/d/1TmDxlU48-738xP8PgF6yEb7CbL8TbH77/edit
Excel Mockup: https://docs.google.com/spreadsheets/d/1SJLUUf4u0RCu9toaueW2iSao-ughOaGbbrvjqV4Sq9I/edit#gid=1163198050

Requested: 

> List of facilities names and items where stock on hand at start of period does not equal stock on hand at end of period

Nb. This doesn't really make sense in a transactional model, but is part of their requests anyway. 

- Filter default to most recent period 
- Find opening balance of the most recent requisition + compare to the closing balance of the previous requisition 

![image](https://user-images.githubusercontent.com/29744386/96798611-c2f0b100-145d-11eb-96ed-d54d8ccce5a6.png)

## Due date 

December 20th 

## Job Code 

JSIFIJ01 | JSI-FIJI-UNFPA Work 2nd half 2020

**Comment by Mai21** [comment]
> Nb. This doesn't really make sense in a transactional model, but is part of their requests anyway.

Anyway created as d2 Data quality
https://demo-board.msupply.org:3000/goto/LtfPQafMk

**Comment by Mai21** [comment]
<table>
<tr><th>Facility</th><td>[store]name, selected facilities</td></tr>
<tr><th>Item</th><td>[item]name = ([item_store_join]store_id), selected items</td></tr>
<tr><th>Period closing</th><td>[requisition_line]stock_on_hand in the previous period user selected</td></tr>
<tr><th>Next period opening</th><td>[requisition_line]stock_on_hand in the selected period</td></tr>
<tr><th>Mismatch</th><td>Yes: Period closing <> Next period opening, Nope: Period closing = Next period opening</td></tr>
</table>
