### ISSUE TITLE
Add Stock Availability dashboard report : D3

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/msupply-dashboard#145]
Original specs: https://docs.google.com/document/d/1TmDxlU48-738xP8PgF6yEb7CbL8TbH77/edit
Excel Mockup: https://docs.google.com/spreadsheets/d/1SJLUUf4u0RCu9toaueW2iSao-ughOaGbbrvjqV4Sq9I/edit#gid=70104762

Requested: 
> - Per product: Name of Facilities 
> with those that are within the parameters and those that are outside: (both overstocked and understocked)
> -Per product-Name of facilities with zero balance

Nb. We should be able to use Andrei's one he did for PNG - interactive bar chart + map, but adding this issue so this can be confirmed. 

## Due date 

December 20th 

## Job Code 

JSIFIJ01 | JSI-FIJI-UNFPA Work 2nd half 2020

**Comment by Mai21** [comment]
https://demo-board.msupply.org:3000/goto/DyNkshfMk  / d3
