### ISSUE TITLE
Add emergency order dashboard report : D4

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/msupply-dashboard#146]
Original specs: https://docs.google.com/document/d/1TmDxlU48-738xP8PgF6yEb7CbL8TbH77/edit
Excel Mockup: https://docs.google.com/spreadsheets/d/1SJLUUf4u0RCu9toaueW2iSao-ughOaGbbrvjqV4Sq9I/edit#gid=208981805

Requested: 

> By month/reporting period and product-List of facilities who have requested an EO 

- Filter for any customer requisitions made with the Emergency order type over a given period 
- Add filters: `Period`, `Item`, `Facility`

![image](https://user-images.githubusercontent.com/29744386/96799137-ecf6a300-145e-11eb-9bc6-b5204fe7240d.png)

## Due date 

December 20th 

## Job Code 

JSIFIJ01 | JSI-FIJI-UNFPA Work 2nd half 2020

**Comment by Mai21** [comment]
Created here
https://demo-board.msupply.org:3000/goto/QgHjFBBGz

**Comment by Mai21** [comment]
<table>
<tr><th>Facility</th><td>[store]name using selected mater list</td></tr>
<tr><th>Item code</th><td>[item]code from selected mater list</td></tr>
<tr><th>Item name</th><td>[item]name from selected mater list</td></tr>
<tr><th>Emergency order submitted</th><td>Yes : Emergency requisition request submitted, Nope : Emergency requisition request not submitted</td></tr>
</table>

Total emergency orders: Count(emergency order submitted = yes)
Number of facilities submitted emergency orders: Count the number of facility

**Comment by anildahalsussol** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DTAC: Dashboard work](https://trello.com/c/ON6vG1yP/422-dtac-dashboard-work)
