### ISSUE TITLE
Add emergency order report - 2  : D5

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/msupply-dashboard#147]
Original specs: https://docs.google.com/document/d/1TmDxlU48-738xP8PgF6yEb7CbL8TbH77/edit
Excel Mockup: https://docs.google.com/spreadsheets/d/1SJLUUf4u0RCu9toaueW2iSao-ughOaGbbrvjqV4Sq9I/edit#gid=561105962

Requested: 

> https://docs.google.com/spreadsheets/d/1SJLUUf4u0RCu9toaueW2iSao-ughOaGbbrvjqV4Sq9I/edit#gid=561105962

- Query for any customer requisitions over the given period with a Closing MOS lower than their Threshold MOS for the program 
- Add filter: `Period`

Note: this is making the assumption that the customer creates a normal requisition at the end of the month, and if they have low stock levels in this requisition, it implies that they SHOULD have made an emergency order earlier.

![image](https://user-images.githubusercontent.com/29744386/96799300-537bc100-145f-11eb-8881-8cf73cfb2c97.png)

## Due date 

December 20th 

## Job Code 

JSIFIJ01 | JSI-FIJI-UNFPA Work 2nd half 2020

**Comment by Mai21** [comment]
@DhanyaHerath 
Is Closing MOS means MOS at the end of the given period? 
We only have "Current MOS" in aggregator table so if "closing MOS" means one at the certain time, we can not make it in the current data structure I guess.

**Comment by Mai21** [comment]
Combined D5 with D4.
https://demo-board.msupply.org:3000/goto/O3fZe8PGk

**Comment by anildahalsussol** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DTAC: Dashboard work](https://trello.com/c/ON6vG1yP/422-dtac-dashboard-work)

**Comment by anildahalsussol** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DTAC: Dashboard work](https://trello.com/c/ON6vG1yP/422-dtac-dashboard-work)
