### ISSUE TITLE
Add Losses/Adjustments dashboard report : D6

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/msupply-dashboard#148]
Original specs: https://docs.google.com/document/d/1TmDxlU48-738xP8PgF6yEb7CbL8TbH77/edit
Excel Mockup: https://docs.google.com/spreadsheets/d/1SJLUUf4u0RCu9toaueW2iSao-ughOaGbbrvjqV4Sq9I/edit#gid=172082813

Requested: 

> List of facility (and product) with loss/adjustments

- Query for all inventory adjustments in the given period 
- Filters: facility, period, item 

![image](https://user-images.githubusercontent.com/29744386/96800861-d6eae180-1462-11eb-9268-29c7c68f2ae7.png)

## Due date 

December 20th 

## Job Code 

JSIFIJ01 | JSI-FIJI-UNFPA Work 2nd half 2020

**Comment by Mai21** [comment]
Created here
https://demo-board.msupply.org:3000/goto/s_aE5EfGk

**Comment by Mai21** [comment]
<table>
<tr><th>Facility</th><td>[store]name using selected mater list</td></tr>
<tr><th>Item code</th><td>[item]code from selected mater list</td></tr>
<tr><th>Item name</th><td>[item]name from selected mater list</td></tr>
<tr><th>Additions</th><td>[transact]pack_size * quantitiy, type=si, name_id = ([name]code = invad), during the filtered time period</td></tr>
<tr><th>Losses</th><td>[transact]pack_size * quantitiy, type=sc, name_id = ([name]code = invad), during the filtered time period</td></tr>
</table>
