### ISSUE TITLE
Add CMS issued stock report : D7

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/msupply-dashboard#149]
Original specs: https://docs.google.com/document/d/1TmDxlU48-738xP8PgF6yEb7CbL8TbH77/edit
Excel Mockup: https://docs.google.com/spreadsheets/d/1SJLUUf4u0RCu9toaueW2iSao-ughOaGbbrvjqV4Sq9I/edit#gid=2106123450

Requested: 

> By Product: quantity distributed from national central level medical stores to lower level facilities nationally (for each reporting period and cumulative)

- Query for all customer invoices in the given period 
- Identify CMS as the store with no supplying store ID (...) 
- Filters:  fromPeriod, toPeriod
- If the two filters are set to the same period - show the items issued for that period. 

![image](https://user-images.githubusercontent.com/29744386/96801211-993a8880-1463-11eb-9324-bcbb86f6f078.png)

## Due date 

December 20th 

## Job Code 

JSIFIJ01 | JSI-FIJI-UNFPA Work 2nd half 2020

**Comment by Mai21** [comment]
https://demo-board.msupply.org:3000/goto/bJ8C0gLGz

**Comment by Mai21** [comment]
<table>
<tr><th>Item code</th><td>[item]code : Amount supplied > 0</td></tr>
<tr><th>Item name</th><td>[item]name : Amount supplied > 0</td></tr>
<tr><th>Amount supplied</th><td>[transact]pack_size * quantitiy, type=ci, status=fn, store_id = 'Tamaki Makaurau warehouse' during the filtered time period</td></tr>
</table>

Considering Tamaki Makaurau warehouse as national central level medical stores on demo. CMS is generally searched by [supplying_store_id = ''] but no data at the moment.
