### ISSUE TITLE
Add ordered vs issued dashboard report : D8

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/msupply-dashboard#150]
Original specs: https://docs.google.com/document/d/1TmDxlU48-738xP8PgF6yEb7CbL8TbH77/edit
Excel Mockup:https://docs.google.com/spreadsheets/d/1SJLUUf4u0RCu9toaueW2iSao-ughOaGbbrvjqV4Sq9I/edit#gid=819283980

Requested: 

> By products-name of facility where order quantity does not equal issue quantity

- Query for all customer requisitions and invoices for a given period 
- Filters: period
- Only include lines where order qty does not match issue qty 
- add up for a period (whole amount ordered per item, whole amount issued per item)

![image](https://user-images.githubusercontent.com/29744386/96801337-d99a0680-1463-11eb-843a-f78a77f0cdde.png)

## Due date 

December 20th 

## Job Code 

JSIFIJ01 | JSI-FIJI-UNFPA Work 2nd half 2020

**Comment by Mai21** [comment]
https://demo-board.msupply.org:3000/goto/TutbMLYMk

**Comment by Mai21** [comment]
<table>
<tr><th>Facility</th><td>[name]name = ([requisition]name_id), selected facilities</td></tr>
<tr><th>Supplier</th><td>[store]name = ([requisition]store_id) </td></tr>
<tr><th>Item code</th><td>[item]code = ([requisition_line]item_id), in selected items</td></tr>
<tr><th>Item name</th><td>[item]name ([requisition_line]item_id), in selected items</td></tr>
<tr><th>Order QTY</th><td>[requisition_line]cust_stock_order during the filtered time period</td></tr>
<tr><th>Issue QTY</th><td>[transact]pack_size * quantitiy, type=ci during the filtered time period</td></tr>
</table>

Showing records with that Order QTY is not equal to Issue QTY
