### ISSUE TITLE
Add MOS Stock availability dashboard report : D10

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/msupply-dashboard#152]
**Original specs:** https://docs.google.com/document/d/1TmDxlU48-738xP8PgF6yEb7CbL8TbH77/edit
**Excel Mockup:** https://docs.google.com/spreadsheets/d/1SJLUUf4u0RCu9toaueW2iSao-ughOaGbbrvjqV4Sq9I/edit#gid=1800056151

Requested: 

> 
> Stocked according to plan- 
> 
> List of all products and stock levels with those that have MOS outside: (both overstocked and understocked) (products organized by MOS from high to low (or low to high)
> 
> List of products with zero balance

NB. See "MOS" on demo-board.mSupply.org, note the filters needed 

## Due date 

December 20th 

## Job Code 

JSIFIJ01 | JSI-FIJI-UNFPA Work 2nd half 2020

**Comment by Mai21** [comment]
https://demo-board.msupply.org:3000/goto/XACMyhfMk / d10 
This report seems similar to d3 so I did in this way; the map and graphs in d3 and the detailed list in d10.

**Comment by Mai21** [comment]
<table>
<tr><th>Facility</th><td>[store]name, selected facilities</td></tr>
<tr><th>Item Code</th><td>[item]code = ([item_store_join]store_id), selected items</td></tr>
<tr><th>Item name</th><td>[item]name = ([item_store_join]store_id), selected items</td></tr>
<tr><th>Pref.pack</th><td>[item]default_pack_size</td></tr>
<tr><th>SOH</th><td>[item_line] stock_on_hand_tot</td></tr>
<tr><th>AMC</th><td>[aggregator]value WHERE dataelement = 'AMC'</td></tr>
<tr><th>MOS</th><td>[aggregator]value WHERE dataelement = 'currentMOS'</td></tr>
<tr><th>SOO</th><td>[purchase_order_line]quan_adjusted_order + [requisition_line]actualquan</td></tr>
</table>
