### ISSUE TITLE
Monthly value of stock ( medicines & medical consumables)

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/msupply-dashboard#155]
Pending further information - unfortunately, this is the only info we have received at present. 

Specs document [here](https://drive.google.com/file/d/1Gt-PdzXlV96QenKPSDrvt3pPSiSemJJs/view?usp=sharing)

![image](https://user-images.githubusercontent.com/29744386/97824261-5197e480-1d20-11eb-93f4-9ec28be9bfc7.png)

In the spreadsheet they've shown one for each of medicines and consumables - maybe could use a filter?
Template from [here](https://docs.google.com/spreadsheets/d/1U7JKXuDSKlozycOA4Iy6uMYaPYAhmaZ7/edit#gid=1771207514)

| Header |  in mSupply | 
|----------| -----------|
|Item code|[item]code|
| Average monthly consumption | Average monthly consumption (AMC) (see aggregator table) | 
| Safety stock (4 months) | 4 *  the Average monthly consumptions | 
|Stock duration/period | MOS which is their current stock on hand/AMC|

**Comment by DhanyaHerath** [comment]
@Mai21 @npendergrast
Link to the Samoa datafile heree: https://drive.google.com/drive/folders/1Wk28rvaN9ByLRBqDf1P9u2nqW6C0s_f_?usp=sharing

It should give you an idea of what categories are used etc.

**Comment by Mai21** [comment]
Thanks! 
It seems like they don't use name category at all. Regarding item category, they only use category 2. They also use master lists.

**Comment by DhanyaHerath** [comment]
Yes that's correct! They do also use [item]user_field_4 to categorise NCD items 
![image](https://user-images.githubusercontent.com/29744386/102300451-d893da00-3fb9-11eb-867f-a6d4f460d919.png)

**Comment by Mai21** [comment]
On the demo dashboard, I created the panels. 

https://demo-board.msupply.org:3000/goto/NktONMBGz
