### ISSUE TITLE
Value of Expired stock as % of Annual Budget

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/msupply-dashboard#156]
Pending further information - unfortunately, this is the only info we have received at present.

Specs document [here](https://drive.google.com/file/d/1Gt-PdzXlV96QenKPSDrvt3pPSiSemJJs/view?usp=sharing)
- Query for all items with an expiry date before the current date
- Each row should be an item line
![image](https://user-images.githubusercontent.com/29744386/99737791-e296fa00-2b2d-11eb-8334-ca05c84ed0c7.png)

Template from [here](https://docs.google.com/spreadsheets/d/1U7JKXuDSKlozycOA4Iy6uMYaPYAhmaZ7/edit#gid=590361538)

**Comment by Mai21** [comment]
On my local with datafile:PNG though, I created it like this so far. I could not find the way to access Grafana samoa, so I keep it on my local at the moment.
![Screen Shot 2020-12-01 at 10 48 37 AM](https://user-images.githubusercontent.com/36495540/100670232-7638b800-33c3-11eb-863f-cf5bb5021927.png)

**Comment by Mai21** [comment]
I created it on demo dashbord
https://demo-board.msupply.org:3000/goto/I-3eDMBGz
