### ISSUE TITLE
Need Province selector field in sync stats dashboard

### ISSUE THREAD

**Issue by Gwalior-84** [openmsupply/msupply-dashboard#158]
Current functioning sync stats dashboard:  https://png.msupply.org:3000/d/KK-crfJWk/sync-statistics-2020?orgId=1&var-sites=All&var-subset=%25&var-nameCategory2=All

We need this developed such that the user can filter by the store Province (Category1_Level2).

**Comment by CarlosNZ** [comment]
@Gwalior-84 I've added a Province filter to this dashboard now, which in turn limits the Stores list (Filter)

Let me know if there's any further tweaks it needs. Otherwise, please close this issue if you're happy with it. Cheers.

**Comment by Gwalior-84** [comment]
Perfect @CarlosNZ !  Thanks.
