### ISSUE TITLE
Summary stats report for DTAC countries

### ISSUE THREAD

**Issue by DhanyaHerath** [openmsupply/msupply-dashboard#197]
The DTAC team would like to have a "report card" dashboard for the countries they are working with. This would display stats that are already available to dashboard users now (eg. last sync date, # of purchase orders created), but with a colour grading and points system to show how they are doing. 

Mockup spreadsheet linked [here](https://docs.google.com/spreadsheets/d/1j-3ntOaizO4Vg6pid2D04RILvb5sGQiJtqOofXgK4NQ/edit#gid=580755755)

Screenshot here: 
![image](https://user-images.githubusercontent.com/29744386/122863893-bcf9f980-d377-11eb-9da3-6abc4c4fc35b.png)

Job code likely: [MFAT_TC2] MFAT Ad hoc help from The mSupply Foundation Activity 1

**Comment by DhanyaHerath** [comment]
Had a chat with @Mai21 and she thought this would take 8 hours max :) 
She also reminded me that Tokelay doesn't have the email plugin set up so we need to account for that time too.

**Comment by anildahalsussol** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DTAC: Dashboard work](https://trello.com/c/ON6vG1yP/422-dtac-dashboard-work)
