### ISSUE TITLE
Dashboard not updating

### ISSUE THREAD

**Issue by Gwalior-84** [openmsupply/msupply-dashboard#201]

**Comment by mark-prins** [comment]
Do you have any more detail? I've had a look at the dashboard and it is reporting correctly what is in the `site` table.
I've cross checked with records in the old dashboard `Sync sites last connection date` report and the values are the same. 

Are there particular stores that aren't updating?

**Comment by mark-prins** [comment]
If anything, the old report is less accurate 😕  What's up with Lae?

### Table

![Screen Shot 2021-09-29 at 10 14 08 AM](https://user-images.githubusercontent.com/9192912/135166694-66ef194d-d774-462c-b662-cd0c9971bcce.png)

### Old report

```
    [
      "Kokopo_AMS",
      "27/09/2021",
      "v4.14 Release 0 Date 07/01/2021 t18:30\\nBuild Tag: V4-14-08\\nBuild Structure: mSupplyV4-14-08\\nBuild Time: Thu, 07 Jan 2021 05:48:34 GMT"
    ],
    ["LAE_AMS", "27/09/2021", "v4.02 Release 0 Date 9/04/2019 t17:45"],
    [
      "Hagen_AMS",
      "28/09/2021",
      "v4.14 Release 0 Date 20/11/2020 t19:05\\nBuild Tag: V4-14-00\\nBuild Structure: mSupplyV4-14-00\\nBuild Time: Fri, 20 Nov 2020 02:26:06 GMT"
    ],
    [
      "Wewak_ams",
      "27/09/2021",
      "v4.14 Release 0 Date 07/01/2021 t18:30\\nBuild Tag: V4-14-08\\nBuild Structure: mSupplyV4-14-08\\nBuild Time: Thu, 07 Jan 2021 05:48:34 GMT"
    ]
```

**Comment by Gwalior-84** [comment]
Sorry @mark-prins I've no memory of creating this issue in github 😞 .  I think things are good.  Please ignore.
