### ISSUE TITLE
Update msupply-dashboard-app plugin with excel-report-email-scheduler plugin

### ISSUE THREAD

**Issue by sworup** [openmsupply/msupply-dashboard#213]
## Description

- mSupply dashboard app plugin has had a major version upgrade. The name itself is too generic and has been replaced with a name that explains the functionality of the plugin better.
- We need to replace the resources of the plugins and replace msupply-dashboard-app plugin with excel-report-email-scheduler plugin in the Dashboard installer.

The plugin repo is: https://github.com/openmsupply/excel-report-email-scheduler
The latest release of the plugin can be found here: https://github.com/openmsupply/excel-report-email-scheduler/releases

## Expected Behavior
- On fresh install the excel-report-email-scheduler should be available to activate by default.
- msupply-dashboard-app should be deprecated.
- The msupply.db and template.slsx files have been incorporated into the installer directory domain so we have make sure the client backs up these files and replaces them.
- One small but breaking change is in msupply.db's `ReportContent` table, the `lookback` field is now of type text instead of number. We have to make that change if we are backing up older db and replacing.

## Current Behavior
- Currently the installer has the older version of the plugin which has some bugs and incompatibilities with Grafana 8.

## Possible Solution
This is not a bug, it is an enhancement

## Steps to Reproduce (bugs only, delete if not applicable)
This is not a bug, it is an enhancement

**Comment by sworup** [comment]
@mark-prins I do not have setup factory installed, so I would update the resources but would have to build an installer. If you want me to do the build I will install setup-factory and do the build. But for now I am gonna put in a PR to master. 

Please comment if you want me to build the installer and create a build.

**Comment by sworup** [comment]
@ujwalSussol @mark-prins it seems I do not have rights to put a PR in this repo. I do not have the rights to set myself as assigned, add label etc. to this repo.

Please grant me the rights.

**Comment by ujwalSussol** [comment]
> @ujwalSussol @mark-prins it seems I do not have rights to put a PR in this repo. I do not have the rights to push a branch to it either. I do not have the rights to set myself as assigned, add label etc. to this issue either. Please give me the rights to do so.

@sworup  : Think I have done it.

**Comment by sworup** [comment]
Thank you, I have the rights now.
