### ISSUE TITLE
Generic dashboard panels

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/msupply-dashboard#3]
Epic for generic dashboard panels.

## High priority

Transactions:

- transactions/stocktakes per store grouped by type (`ci`, `si`, etc.)
- last `n` transactions per store
- % of purchase value (`trans_line.price_extension`) being catalogue (item code ending in 00), excluding stock transfers and inventory adjustments.
- % of outstanding goods value (`purchase_order_line.price_expected_after_discount`) associated with partial POs (partial/open POs).

Stock:

- total stock overview by store
- total `MOC` by item

## Medium priority

Other suggested panels are listed [here](https://sussol.net/wiki/doku.php/msupply:planning:projects:notifications#subject_of_notification).

**Comment by wlthomson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create library of panels (dashboard charts and other elements)](https://trello.com/c/F9fUwUgO/4-create-library-of-panels-dashboard-charts-and-other-elements)

**Comment by mark-prins** [comment]
https://github.com/openmsupply/msupply-dashboard/tree/master/library

**Comment by wlthomson** [comment]
Looks like this is done. Closing.
