### ISSUE TITLE
Panel for percentage of non-catalogue purchases

### ISSUE THREAD

**Issue by wlthomson** [openmsupply/msupply-dashboard#4]
PNG have requested a dashboard panel showing the percentage of total purchase value (`trans_line.price_extension`) associated with catalogue items (item code ending in 00). The calculation should exclude stock transfers and inventory adjustments.

**Comment by wlthomson** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add panel for 'percentage of non-catalogue purchases'](https://trello.com/c/82RXK5KW/23-add-panel-for-percentage-of-non-catalogue-purchases)

**Comment by DhanyaHerath** [comment]
"Non-catalogue Items Purchase Orders" panel in the Overview/KPIs dashboard
