### ISSUE TITLE
User permissions

### ISSUE THREAD

**Issue by andreievg** [openmsupply/msupply-dashboard#61]
I've been meaning to write this out awhile ago, better late then never, this is one idea of how we can handle finer grained user permissions (looks like it can be done for Grafana Enterprise (paid version), but not for the free version.

### Exposing Grafana User to SQL

Can hard code a variable `$grafanaUser`

![Screen Shot 2020-02-17 at 3 24 41 PM](https://user-images.githubusercontent.com/26194949/74619250-b82ca080-5199-11ea-8be2-9eb9ae85ef34.png)

With this small change, we can access $grafanaUser as a template variable (will give the name of currently logged in user)

### Permission Restriction

Instead of restricting each sql query, we can restrict what facilities and items appear in filters, using user, `user_store` table and some master list -> user association

### Restricting Store

Can use `user_store` table to figure out which stores user 'can login to'. A helper `view` can be quite useful, would envision a filter like this:

`select name from store where name like '% AMS' and ID in (select ID from userStores($grafanaUser))`

### Restricting Items

Need to create a join table between user and master list, similar to store it will allow the following filter restriction.

`select item_name from item where ID  (select ID from userItems($grafanaUser))`

**Comment by mark-prins** [comment]
Nice! I was thinking to use `user_store` as well, to bring permissions across from mSupply. looks like a neat solution

**Comment by andreievg** [comment]
looks like __user.login is provided by grafana now
