### ISSUE TITLE
Review of Laos dashboard

### ISSUE THREAD

**Issue by mark-prins** [openmsupply/msupply-dashboard#65]
Will need a review, the dashboard hasn't been updated post installation.
Perhaps add a map panel for months of stock

**Comment by CarlosNZ** [comment]
> Perhaps add a map panel for months of stock

Looks like all the latitude/longitude values are 0,0. That's the only way to get info for maps, right?

**Comment by mark-prins** [comment]
yep, it is. We can do a region map as well, but that is more work because we'd have to generate geojson values.

Should say that we have reviewed the Laos dashboard now. Mentioned the need for co-ordinates, but might not hold our breath. other priorities right now!
