### ISSUE TITLE
Custom Map panel -- GeoJSON overlay obscures click-through

### ISSUE THREAD

**Issue by CarlosNZ** [openmsupply/msupply-dashboard#82]
Just noticed that with the new GeoJSON overlay layer, the map circles that are fully contained within the overlay fill are not clickable. I assume the region layer is obscuring the target area and preventing it from responding to click events.

Hopefully it's a simple tweak to change the rendering order so that the circles are the top-most?

(If it's not that simple, then maybe we can set `fill` back to `false` in the meantime to keep the click-thru functionality?)

**Comment by CarlosNZ** [comment]
Also, due to the same issue, the "hover-over" tooltips don't appear when the map circles are beneath the fill layer.

**Comment by mark-prins** [comment]
Done. PR coming soon.

**Comment by CarlosNZ** [comment]
Fixed in #86
