### ISSUE TITLE
Improve 'Mobile' sync stats dashboard panel

### ISSUE THREAD

**Issue by Gwalior-84** [openmsupply/msupply-dashboard#92]
## Describe the bug

The current 'State of synchronisation by site' panel has a number of issues:

For a start, this panel is missing many stores and it is unclear how to cause a store to be included.

- **All columns**:  There is no legend to let us know what the colour scalings are  Yes, we can edit the panel to see what they are, but a user won't be able to do that.
- **Days since last SYNC** column:  When the value is reported as 50, it's often actually more than that.
- **CIs per day**  It's not clear over how many days this calculation has been done.  On examination, the values are too low when looking over the last month, which seems a reasonable period...  
- **Export Date**  A cryptic title...  Is this the date that the data was exported from mSupply?  Was this inserted for debugging purposes?  It's the same for every line in the table...  This figure is handy, but does it need to be on every line?

![image](https://user-images.githubusercontent.com/9062300/81379009-abda3300-914b-11ea-9525-a7b28f97a308.png)

## To Reproduce

https://png.msupply.org:3000/d/n9KzlfJWz/sync-statistics?orgId=1

## Expected behaviour

- Missing stores:  A selector at the top should allow selection of stores individually, or by tag.
- **All columns**:  Is there a way for a legend, that is dynamically updated by the configuration, to pop up?  I realise that each column would have its own legend...
- **Days since last SYNC** column:  This should report the correct number.
- **CIs per day**  This should be calculated over the last month, and that fact be visible somewhere (a pop-up?)
- **Export Date**  A single date and time stamp somewhere on the dashboard indicating 'Valid as of...'

## Versions (please complete the following information)
 - mSupply Version 4.7
 
## Users affected

PNG - WV

## Additional context

I understand this particular panel uses 'older technology'.  I'm quite happy with replacing it with newer technology...  it does look a bit clunky.

**Comment by mark-prins** [comment]
thanks @Gwalior-84 - appreciate the feedback! 
Will aim to do this next week

**Comment by CarlosNZ** [comment]
Hi @Gwalior-84,

as a start, I've put a new version of this dashboard at https://png.msupply.org:3000/d/KK-crfJWk/sync-statistics-2020?orgId=1.

It's basically the same, but the query uses direct SQL queries rather the `dashboard_reports` aggregations, so the info is up to date with the dashboard as a whole, and all stores should be available.

It's currently in the Develop folder, but we can move it over to the main folder once we're happy with it (or feel free to do it yourself).

Doesn't look like we can add a legend in any straightforward way -- although I'd argue that it should be pretty clear that "green = good" and "red = bad" and the exact thresholds are not particularly important unless they're drastically misleading.

Anyway, let us know what else you'd like and we'll keep chipping away at it, if possible.

**Comment by mark-prins** [comment]
Thanks @CarlosNZ!! I've been intending to look at this for a number of weeks 😄 
I've added a static legend, as an example of a possibility - using the text panel. Not ideal, but more informative than nothing?

**Comment by Gwalior-84** [comment]
Thanks @CarlosNZ and @mark-prins for looking in to this.

I'm inclined to agree with your reasoning Carl on why we can live without the legend.  I appreciate what you've done Mark to make one up.  That's certainly the approach we can use if clients require it.

There are still issues with this dashboard:

1. Badili AMS site definitely has synced recently.  Why is there no number here?
2. Alotau Malaria Store is on the Primary, so is in a constant state of sync.  What is this actually measuring?
3. Virtually all stores have had a stocktake...
4. What does a blank here mean?  No requisition?  If there has never been a requisition, what number would appear here?
5. Some (all?) of these numbers are wrong.  E.g. Badili AMS does several per day.

![image](https://user-images.githubusercontent.com/9062300/84961006-8d058e00-b146-11ea-9b95-6433ff3e7290.png)

**Comment by mark-prins** [comment]
Hi @Gwalior-84 

> Badili AMS site definitely has synced recently. Why is there no number here?

Each store has a sync ID and this is used internally to track the sync date. The code which updates the 'sync dates' table in the dashboard is exporting the first store with a matching sync ID 🙄 
Badili AMS has a sync ID of `5` - turns out that there are nine stores who have a sync ID of `5`:
- Dental Central Store
- Malaria Central Store
- TB Central Store
- Badili AMS
- HIV Central Store
- EPI Central Store
- Badili AMS Dispensary
- RH Central Store
- COVID-19

If this configuration is valid - we'll need to modify the dashboard export, to account for multiple stores having the same ID

> Alotau Malaria Store is on the Primary, so is in a constant state of sync. What is this actually measuring?

Alotau suffers the same fate ( though worse, there are 29 stores with a sync ID of `1` )

> Virtually all stores have had a stocktake...

Uh. Oops. The `Stock_take` table wasn't included in the export. It is now.

> What does a blank here mean? No requisition? If there has never been a requisition, what number would appear here?

None in the last 50 days. I've amended the table to show `50+` rather than `-` : does that help?

> Some (all?) of these numbers are wrong. E.g. Badili AMS does several per day.

This is due to the query, which was taking all transactions in the current month. Which is particularly daft when you look at the dashboard on the 1st of the month 🙄  I've changed to 'the last 30 days' which is a little better.

**Comment by mark-prins** [comment]
Raised an mSupply issue to resolve the export: https://github.com/sussol/msupply/issues/6481

**Comment by Gwalior-84** [comment]
Thanks for looking in to this @mark-prins 

> 
> 
> Hi @Gwalior-84
> 
> > Badili AMS site definitely has synced recently. Why is there no number here?
> 
> Each store has a sync ID and this is used internally to track the sync date. The code which updates the 'sync dates' table in the dashboard is exporting the first store with a matching sync ID 🙄
> Badili AMS has a sync ID of `5` - turns out that there are nine stores who have a sync ID of `5`:
> 
>     * Dental Central Store
>     * Malaria Central Store
>     * TB Central Store
>     * Badili AMS
>     * HIV Central Store
>     * EPI Central Store
>     * Badili AMS Dispensary
>     * RH Central Store
>     * COVID-19
> 
> If this configuration is valid - we'll need to modify the dashboard export, to account for multiple stores having the same ID

Yes, this configuration is valid.  Each store having a unique sync ID is only valid for mSupply Mobile stores.

> 
> > Alotau Malaria Store is on the Primary, so is in a constant state of sync. What is this actually measuring?
> 
> Alotau suffers the same fate ( though worse, there are 29 stores with a sync ID of `1` )
> 

Exactly.  I suggest all stores on the primary should all have a 'Days since last Sync' of `1`.

> > Virtually all stores have had a stocktake...
> 
> Uh. Oops. The `Stock_take` table wasn't included in the export. It is now.
> 

Thanks.

> > What does a blank here mean? No requisition? If there has never been a requisition, what number would appear here?
> 
> None in the last 50 days. I've amended the table to show `50+` rather than `-` : does that help?
> 

Most sites in they system I am familiar with should do a requisition only every 60 days.  Also, sites with `50+` are not highlighted in red - which is what they should be.  Please change this to the actual number of days, which should fix the highlighting, right?

> > Some (all?) of these numbers are wrong. E.g. Badili AMS does several per day.
> 
> This is due to the query, which was taking all transactions in the current month. Which is particularly daft when you look at the dashboard on the 1st of the month 🙄 I've changed to 'the last 30 days' which is a little better.

Yes, much better, thanks.

**Comment by mark-prins** [comment]
Thanks @Gwalior-84!

> Please change this to the actual number of days

Done. Although I've changed the query to limit to 100 days rather than removing entirely - removing the limit on all the subqueries made the panel way too slow.
There are some which return no results - for these I've gone with the same pattern, and show `100+` rather than `-` Can do either, and retain the red highlighting.

> but it is still producing incorrect results

I re-read what the intention was. The query was giving you the number of distinct days on which a ci was made, over the last 30 days. Don't know if that's helpful; so I've changed the query to match what the heading is telling us: the *actual* number of ci's over the last 30 days. Is that more better?

**Comment by Gwalior-84** [comment]
Thanks @mark-prins 


> 
> Thanks @Gwalior-84!
> 
> > Please change this to the actual number of days
> 
> Done. Although I've changed the query to limit to 100 days rather than removing entirely - removing the limit on all the subqueries made the panel way too slow.

OK, now I understand the reason for the limit!  100 days is > 1 quarter, which might be the longest reasonable interval between requisitions.  100 is good.

> There are some which return no results - for these I've gone with the same pattern, and show `100+` rather than `-` Can do either, and retain the red highlighting.

Yes, that makes sense.

> 
> > but it is still producing incorrect results
> 
> I re-read what the intention was. The query was giving you the number of distinct days on which a ci was made, over the last 30 days. Don't know if that's helpful; so I've changed the query to match what the heading is telling us: the _actual_ number of ci's over the last 30 days. Is that more better?

Yes, _Actual_ number over the last 30 days is good.

Thanks!

**Comment by Gwalior-84** [comment]
Appears to be resolved.  https://png.msupply.org:3000/d/KK-crfJWk/sync-statistics-2020?orgId=1&var-sites=All&var-subset=%25&var-nameCategory2=All
